name: Build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  
jobs:
    build:
      runs-on: [ubuntu-latest]
      permissions:
        contents: write

      env:
          SOURCEMOD_URL: https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6936-linux.tar.gz
          SOURCEMOD: $GITHUB_WORKSPACE/../sourcemod/addons/sourcemod/scripting
          PLUGIN: $GITHUB_WORKSPACE/addons/sourcemod/scripting

      steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
            submodules: true

        - name: Download sourcemod
          run: |
            cd ..
            mkdir sourcemod
            cd sourcemod
            wget -O sourcemod.tar.gz ${{ env.SOURCEMOD_URL }}
            tar -xf sourcemod.tar.gz
            
        - name: Setup dependencies
          run: |
            cd ${{ env.PLUGIN }}
            mkdir -p include
            mkdir -p ../plugins

        - name: Build plugin
          run: |        
              cd ${{ env.PLUGIN }}
              ${{ env.SOURCEMOD }}/spcomp64 ./hello-world.sp -o ../plugins/hello-world.smx -i ./include

        - name: Commit file
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Auto build smx file

